# Generated by Django 5.1 on 2024-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.CharField(max_length=100, verbose_name='Shipping Address'),
        ),
    ]
