# Generated by Django 5.1 on 2024-11-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_phone_alter_profile_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='_', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
