# Generated by Django 5.1 on 2024-11-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_city_profile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Phone'),
        ),
    ]
