# Generated by Django 5.1 on 2024-12-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_first_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_purchase',
        ),
    ]
