# Generated by Django 5.1 on 2024-11-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SHIPPED'), ('D', 'DELIVERED'), ('C', 'CANCELED')], default='P', max_length=1),
        ),
    ]
