# Generated by Django 5.1 on 2024-12-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.PositiveSmallIntegerField(default=3000)),
                ('delivery_time', models.CharField(default='1-3 business days', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delivery'),
        ),
    ]
