# Generated by Django 5.1 on 2025-01-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delivery_order_delivery_fee_order_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
    ]
