# Generated by Django 5.1 on 2024-11-13 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HappyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.URLField(blank=True, null=True)),
                ('tw', models.URLField(blank=True, null=True)),
                ('ln', models.URLField(blank=True, null=True)),
                ('be', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='Clothing Store', max_length=255)),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum')),
                ('phone', models.CharField(default='+2348029874990', max_length=20)),
                ('address', models.CharField(default='23, Lagos, Nigeria', max_length=500)),
                ('email', models.EmailField(default='praizthecoder@gmail.com', max_length=254)),
                ('map_url', models.URLField(default='https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed')),
                ('company_socials', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.social')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('CO-Founder', 'CO-Founder'), ('Product Expert', 'Product Expert'), ('Chief Marketing', 'Chief Marketing'), ('Product Specialist', 'Product Specialist'), ('Product Photographer', 'Product Photographer'), ('General Manager', 'General Manager')], max_length=255)),
                ('description', models.TextField()),
                ('avatar', models.ImageField(upload_to='team/')),
                ('social_links', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.social')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
