# Generated by Django 5.1 on 2024-11-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_customer_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
