# Generated by Django 5.1 on 2024-12-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_phone'),
        ('shop', '0004_rename_user_wishlist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
